In [1]:
import pandas as pd

print("Milestone 2 Started Successfully!")

Milestone 2 Started Successfully!

In [5]:
import pandas as pd

network = pd.read_csv("C:\MetroFlow\dataset\Delhi-Metro-Network.csv")

network.head()

,Station ID,Station Name,Distance from Start (km),Line,Opening Date,Station Layout,Latitude,Longitude
0,1,Jhil Mil,10.3,Red line,2008-04-06,Elevated,28.675790,77.312390
1,2,Welcome [Conn: Red],46.8,Pink line,2018-10-31,Elevated,28.671800,77.277560
2,3,DLF Phase 3,10.0,Rapid Metro,2013-11-14,Elevated,28.493600,77.093500
3,4,Okhla NSIC,23.8,Magenta line,2017-12-25,Elevated,28.554483,77.264849
4,5,Dwarka Mor,10.2,Blue line,2005-12-30,Elevated,28.619320,77.033260

In [6]:
network.info()

<class 'pandas.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Station ID                285 non-null    int64
 1   Station Name              285 non-null    str
 2   Distance from Start (km)  285 non-null    float64
 3   Line                      285 non-null    str
 4   Opening Date              285 non-null    str
 5   Station Layout            285 non-null    str
 6   Latitude                  285 non-null    float64
 7   Longitude                 285 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 17.9 KB

In [7]:
network.columns

Index(['Station ID', 'Station Name', 'Distance from Start (km)', 'Line',
       'Opening Date', 'Station Layout', 'Latitude', 'Longitude'],
      dtype='str')

In [8]:
network.shape

(285, 8)

In [1]:
import pandas as pd

entry_exit = pd.read_excel("C:\MetroFlow\dataset\multi-year-station-entry-and-exit-figures.xls")

entry_exit.head()

                                               Notes
0                                                NaN
1  Annual figures are calculated as entries plus ...
2  This weighting is based on the assumption that...
3  and grossing up to a 364 day year excluding Ch...
4  This adjustment does not change from year to y...

In [2]:
entry_exit.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Notes   17 non-null     object
dtypes: object(1)
memory usage: 332.0+ bytes

In [3]:
entry_exit.columns

Index(['Notes'], dtype='str')

In [4]:
entry_exit.head()

                                               Notes
0                                                NaN
1  Annual figures are calculated as entries plus ...
2  This weighting is based on the assumption that...
3  and grossing up to a 364 day year excluding Ch...
4  This adjustment does not change from year to y...

In [2]:
import pandas as pd

xls = pd.ExcelFile(r"C:\MetroFlow\dataset\multi-year-station-entry-and-exit-figures.xls")

print(xls.sheet_names)

['Notes', '2017 Entry & Exit', '2016 Entry & Exit', '2015 Entry & Exit', '2014 Entry & Exit', '2013 Entry & Exit', '2012 Entry & Exit', '2011 Entry & Exit', 'workings', '2010 Entry & Exit', '2009 Entry & Exit', '2008 Entry & Exit', '2007 Entry & Exit', 'Sheet1']

In [3]:
import pandas as pd

entry_exit = pd.read_excel(
    r"C:\MetroFlow\dataset\multi-year-station-entry-and-exit-figures.xls",
    sheet_name="2017 Entry & Exit"
)

entry_exit.head()

,COUNTS - 2017 - annual entries & exits,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,"(C) Copyright, London Underground Limited, 2018",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,[ Weights,253,52,59,253,52,59,]
3,Counts by station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annual
4,,NaN,NaN,NaN,Entry,Entry,Entry,Exit,Exit,Exit,Entry + Exit

In [4]:
entry_exit.info()

<class 'pandas.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 11 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   COUNTS - 2017 - annual entries & exits  272 non-null    object
 1   Unnamed: 1                              269 non-null    str
 2   Unnamed: 2                              269 non-null    str
 3   Unnamed: 3                              261 non-null    str
 4   Unnamed: 4                              271 non-null    object
 5   Unnamed: 5                              271 non-null    object
 6   Unnamed: 6                              271 non-null    object
 7   Unnamed: 7                              271 non-null    object
 8   Unnamed: 8                              271 non-null    object
 9   Unnamed: 9                              271 non-null    object
 10  Unnamed: 10                             272 non-null    object
dtypes: object(8), str(3)
memory usage: 23.7+ KB

In [5]:
entry_exit = pd.read_excel(
    r"C:\MetroFlow\dataset\multi-year-station-entry-and-exit-figures.xls",
    sheet_name="2017 Entry & Exit",
    header=6
)

entry_exit.head()

,nlc,Station,Borough,Note,Weekday,Saturday,Sunday,Weekday.1,Saturday.1,Sunday.1,million
0,625,King's Cross St. Pancras,Camden,,149150,117237,98579,146864,112360,89348,97.918279
1,747,Waterloo,Lambeth,T,147574,91841,55080,149577,90703,56770,91.270641
2,669,Oxford Circus,City of Westminster,,121364,103026,63185,136405,113894,65547,84.090585
3,741,Victoria,City of Westminster,,121018,88605,69760,122783,91001,71565,79.359340
4,635,London Bridge,Southwark,,113606,78569,45408,107048,75800,42694,69.050668

In [6]:
entry_exit.shape

(268, 11)

In [7]:
entry_exit.isnull().sum()

nlc           0
Station       0
Borough       0
Note          9
Weekday       0
Saturday      0
Sunday        0
Weekday.1     0
Saturday.1    0
Sunday.1      0
million       0
dtype: int64

In [8]:
entry_exit.describe()

,nlc,Weekday,Saturday,Sunday,Weekday.1,Saturday.1,Sunday.1,million
count,268.00000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,644.13806,17512.313433,12152.365672,8434.824627,17143.664179,11788.981343,8169.488806,10.992567
std,85.03513,23316.866289,17172.432499,12049.522130,23413.082674,17224.040183,11640.988875,14.814015
min,500.00000,618.000000,215.000000,117.000000,704.000000,178.000000,112.000000,0.368413
25%,571.75000,5271.500000,3414.250000,2284.250000,4881.250000,3267.250000,2319.000000,3.200756
50%,640.50000,9483.500000,6382.500000,4244.500000,9184.500000,5912.000000,4229.500000,5.884430
75%,715.25000,20435.000000,12692.500000,9023.250000,19935.250000,12538.750000,8735.000000,12.650982
max,884.00000,149150.000000,117237.000000,98579.000000,149577.000000,113894.000000,89348.000000,97.918279

In [9]:
import pandas as pd

delays = pd.read_csv(r"C:\MetroFlow\dataset\public_transport_delays.csv")

delays.head()

,trip_id,date,time,transport_type,route_id,origin_station,destination_station,scheduled_departure,scheduled_arrival,actual_departure_delay_min,...,wind_speed_kmh,precipitation_mm,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,season,delayed
0,T00000,2023-01-01,05:00:00,Tram,Route_15,Station_31,Station_6,05:02:00,05:55:00,12,...,46,13.0,NaN,500,81,0,1,6,Winter,0
1,T00001,2023-01-01,05:15:00,Metro,Route_12,Station_49,Station_32,05:16:00,05:55:00,15,...,11,11.4,NaN,0,53,0,0,6,Autumn,1
2,T00002,2023-01-01,05:30:00,Bus,Route_16,Station_29,Station_42,05:33:00,06:17:00,0,...,31,14.1,Sports,0,67,1,0,6,Autumn,0
3,T00003,2023-01-01,05:45:00,Tram,Route_19,Station_26,Station_18,05:49:00,06:08:00,15,...,41,6.4,NaN,500,84,0,0,6,Winter,1
4,T00004,2023-01-01,06:00:00,Tram,Route_8,Station_18,Station_15,06:00:00,06:35:00,-1,...,30,18.5,NaN,500,46,0,0,6,Spring,1

In [10]:
delays.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     2000 non-null   str
 1   date                        2000 non-null   str
 2   time                        2000 non-null   str
 3   transport_type              2000 non-null   str
 4   route_id                    2000 non-null   str
 5   origin_station              2000 non-null   str
 6   destination_station         2000 non-null   str
 7   scheduled_departure         2000 non-null   str
 8   scheduled_arrival           2000 non-null   str
 9   actual_departure_delay_min  2000 non-null   int64
 10  actual_arrival_delay_min    2000 non-null   int64
 11  weather_condition           2000 non-null   str
 12  temperature_C               2000 non-null   float64
 13  humidity_percent            2000 non-null   int64
 14  wind_speed_kmh              2000 non-null   int64
 15  precipitation_mm            2000 non-null   float64
 16  event_type                  827 non-null    str
 17  event_attendance_est        2000 non-null   int64
 18  traffic_congestion_index    2000 non-null   int64
 19  holiday                     2000 non-null   int64
 20  peak_hour                   2000 non-null   int64
 21  weekday                     2000 non-null   int64
 22  season                      2000 non-null   str
 23  delayed                     2000 non-null   int64
dtypes: float64(2), int64(10), str(12)
memory usage: 375.1 KB

In [11]:
delays.columns

Index(['trip_id', 'date', 'time', 'transport_type', 'route_id',
       'origin_station', 'destination_station', 'scheduled_departure',
       'scheduled_arrival', 'actual_departure_delay_min',
       'actual_arrival_delay_min', 'weather_condition', 'temperature_C',
       'humidity_percent', 'wind_speed_kmh', 'precipitation_mm', 'event_type',
       'event_attendance_est', 'traffic_congestion_index', 'holiday',
       'peak_hour', 'weekday', 'season', 'delayed'],
      dtype='str')

In [12]:
stations = pd.read_csv(r"C:\MetroFlow\dataset\Stations_20220221.csv")

stations.head()

,NLC,NAME,EASTING,NORTHING,LINES,NETWORK,London Underground,Elizabeth Line,London Overground,DLR,Zone,x,y,Night Tube?
0,500,Acton Town,519478,179592,"District, Piccadilly",London Underground,Yes,NaN,NaN,NaN,3,-0.278433,51.502137,Yes
1,501,Barbican,532004,181856,"Circle, Hammersmith & City, Metropolitan",London Underground,Yes,NaN,NaN,NaN,1,-0.097190,51.519699,No
2,502,Aldgate,533613,181262,"Circle, Metropolitan",London Underground,Yes,NaN,NaN,NaN,1,-0.074236,51.513982,No
3,503,Aldgate East,533936,181375,"District, Hammersmith & City",London Underground,Yes,NaN,NaN,NaN,1,-0.069540,51.514917,No
4,504,Stratford International DLR,538128,184761,DLR,NaN,NaN,NaN,NaN,Yes,"2,3",-0.007832,51.544339,No

In [13]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NLC                 471 non-null    int64
 1   NAME                471 non-null    str
 2   EASTING             471 non-null    int64
 3   NORTHING            471 non-null    int64
 4   LINES               471 non-null    str
 5   NETWORK             309 non-null    str
 6   London Underground  270 non-null    str
 7   Elizabeth Line      41 non-null     str
 8   London Overground   113 non-null    str
 9   DLR                 45 non-null     str
 10  Zone                471 non-null    str
 11  x                   471 non-null    float64
 12  y                   471 non-null    float64
 13  Night Tube?         471 non-null    str
dtypes: float64(2), int64(3), str(9)
memory usage: 51.6 KB

In [14]:
stations.columns

Index(['NLC', 'NAME', 'EASTING', 'NORTHING', 'LINES', 'NETWORK',
       'London Underground', 'Elizabeth Line', 'London Overground', 'DLR',
       'Zone', 'x', 'y', 'Night Tube?'],
      dtype='str')

In [15]:
stations.shape

(471, 14)

In [16]:
tfl = pd.read_csv(r"C:\MetroFlow\dataset\TfL_stations.csv")

tfl.head()

,Unnamed: 0,NLC,Station,En/Ex 2007,En/Ex 2008,En/Ex 2009,En/Ex 2010,En/Ex 2011,En/Ex 2012,En/Ex 2013,...,En/Ex 2019,En/Ex 2020,En/Ex 2021,LINES,NETWORK,London Underground,Elizabeth Line,London Overground,DLR,Night Tube?
0,0,500.0,Acton Town,5773625.0,5816798.0,5459521.0,5428316.0,5462387.0,5584934.0,5748994.0,...,6186555.0,3568528.0,2902697.0,"District, Piccadilly",London Underground,Yes,NaN,NaN,NaN,Yes
1,1,501.0,Barbican,9558748.0,10030975.0,9261249.0,8873092.0,9228704.0,9850562.0,10464425.0,...,10467974.0,2537108.0,3467856.0,"Circle, Hammersmith & City, Metropolitan",London Underground,Yes,NaN,NaN,NaN,No
2,2,502.0,Aldgate,5572412.0,6243135.0,5974176.0,6026534.0,6235513.0,6647283.0,6877712.0,...,9956600.0,2775844.0,3525128.0,"Circle, Metropolitan",London Underground,Yes,NaN,NaN,NaN,No
3,3,503.0,Aldgate East,7657338.0,8152761.0,9047885.0,8974956.0,9157483.0,10134021.0,11663144.0,...,14148654.0,3144899.0,5611130.0,"District, Hammersmith & City",London Underground,Yes,NaN,NaN,NaN,No
4,4,505.0,Alperton,3005522.0,3072270.0,3044399.0,2942987.0,2945259.0,2893236.0,2956888.0,...,2858439.0,2064990.0,1345253.0,Piccadilly,London Underground,Yes,NaN,NaN,NaN,No

In [17]:
tfl.info()

<class 'pandas.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          436 non-null    int64
 1   NLC                 436 non-null    float64
 2   Station             436 non-null    str
 3   En/Ex 2007          273 non-null    float64
 4   En/Ex 2008          268 non-null    float64
 5   En/Ex 2009          268 non-null    float64
 6   En/Ex 2010          268 non-null    float64
 7   En/Ex 2011          268 non-null    float64
 8   En/Ex 2012          268 non-null    float64
 9   En/Ex 2013          268 non-null    float64
 10  En/Ex 2014          268 non-null    float64
 11  En/Ex 2015          268 non-null    float64
 12  En/Ex 2016          268 non-null    float64
 13  En/Ex 2017          408 non-null    float64
 14  En/Ex 2018          417 non-null    float64
 15  En/Ex 2019          417 non-null    float64
 16  En/Ex 2020          427 non-null    float64
 17  En/Ex 2021          429 non-null    float64
 18  LINES               428 non-null    str
 19  NETWORK             270 non-null    str
 20  London Underground  270 non-null    str
 21  Elizabeth Line      38 non-null     str
 22  London Overground   112 non-null    str
 23  DLR                 45 non-null     str
 24  Night Tube?         428 non-null    str
dtypes: float64(16), int64(1), str(8)
memory usage: 85.3 KB

In [18]:
tfl.columns

Index(['Unnamed: 0', 'NLC', 'Station', 'En/Ex 2007', 'En/Ex 2008',
       'En/Ex 2009', 'En/Ex 2010', 'En/Ex 2011', 'En/Ex 2012', 'En/Ex 2013',
       'En/Ex 2014', 'En/Ex 2015', 'En/Ex 2016', 'En/Ex 2017', 'En/Ex 2018',
       'En/Ex 2019', 'En/Ex 2020', 'En/Ex 2021', 'LINES', 'NETWORK',
       'London Underground', 'Elizabeth Line', 'London Overground', 'DLR',
       'Night Tube?'],
      dtype='str')

In [19]:
tfl.shape

(436, 25)

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\MetroFlow\dataset\Delhi-Metro-Network.csv")

print(df.columns.tolist())
print(df.head())

['Station ID', 'Station Name', 'Distance from Start (km)', 'Line', 'Opening Date', 'Station Layout', 'Latitude', 'Longitude']
   Station ID         Station Name  Distance from Start (km)          Line  \
0           1             Jhil Mil                      10.3      Red line
1           2  Welcome [Conn: Red]                      46.8     Pink line
2           3          DLF Phase 3                      10.0   Rapid Metro
3           4           Okhla NSIC                      23.8  Magenta line
4           5           Dwarka Mor                      10.2     Blue line

  Opening Date Station Layout   Latitude  Longitude
0   2008-04-06       Elevated  28.675790  77.312390
1   2018-10-31       Elevated  28.671800  77.277560
2   2013-11-14       Elevated  28.493600  77.093500
3   2017-12-25       Elevated  28.554483  77.264849
4   2005-12-30       Elevated  28.619320  77.033260

: