In [1]:
import pandas as pd
import numpy as np

In [8]:
stations = pd.read_json("../datasets/stations.json")

trains = pd.read_json("../datasets/trains.json")

schedule = pd.read_json("../datasets/schedules.json")

In [3]:
stations = pd.json_normalize(stations["features"])

stations.head()

,type,geometry.type,geometry.coordinates,properties.state,properties.code,properties.name,properties.zone,properties.address,geometry
0,Feature,Point,"[75.4516454, 27.2520587]",Rajasthan,BDHL,Badhal,NWR,"Kishangarh Renwal, Rajasthan",NaN
1,Feature,NaN,NaN,NaN,XX-BECE,XX-BECE,NaN,NaN,NaN
2,Feature,NaN,NaN,NaN,XX-BSPY,XX-BSPY,NaN,NaN,NaN
3,Feature,NaN,NaN,NaN,YY-BPLC,YY-BPLC,NaN,NaN,NaN
4,Feature,Point,"[79.519746, 28.913427000000002]",Uttar Pradesh,KHH,KICHHA,NER,"Kichha, Uttar Pradesh",NaN

In [4]:
trains = pd.json_normalize(trains["features"])

trains.head()

,type,geometry.type,geometry.coordinates,properties.third_ac,properties.arrival,properties.from_station_code,properties.name,properties.zone,properties.chair_car,properties.first_class,...,properties.departure,properties.return_train,properties.to_station_code,properties.second_ac,properties.classes,properties.to_station_name,properties.duration_h,properties.type,properties.first_ac,properties.distance
0,Feature,LineString,"[[74.880117, 32.706975], [74.953339, 32.762368...",0,12:15:00,JAT,Jammu Tawi Udhampur Special,NR,0,0,...,10:40:00,04602,UHP,0,,UDHAMPUR,1.0,DEMU,0,53.0
1,Feature,LineString,"[[75.154881, 32.92664], [75.14542599999999, 32...",0,08:35:00,UHP,UDHAMPUR JAMMUTAWI DMU,NR,0,0,...,06:45:00,04601,JAT,0,,JAMMU TAWI,1.0,DEMU,0,53.0
2,Feature,LineString,"[[74.880117, 32.706975], [74.953339, 32.762368...",0,17:50:00,JAT,JAT UDAHMPUR DMU,NR,0,0,...,16:15:00,04604,UHP,0,,UDHAMPUR,1.0,DEMU,0,53.0
3,Feature,LineString,"[[75.154881, 32.92664], [75.14542599999999, 32...",0,19:50:00,UHP,UDHAMPUR JAMMUTAWI DMU,NR,0,0,...,18:20:00,04603,JAT,0,,JAMMU TAWI,1.0,DEMU,0,53.0
4,Feature,LineString,"[[72.840535, 19.061911], [72.840078, 19.069166...",1,12:30:00,BDTS,Mumbai BandraT-Bikaner SF Special,NWR,0,0,...,14:35:00,04727,BKN,1,,BIKANER JN,21.0,SF,0,1212.0

In [9]:
schedule.columns

Index(['arrival', 'day', 'train_name', 'station_name', 'station_code', 'id',
       'train_number', 'departure'],
      dtype='str')

In [10]:
schedule.head()

,arrival,day,train_name,station_name,station_code,id,train_number,departure
0,None,1.0,Falaknuma Lingampalli MMTS,KACHEGUDA FALAKNUMA,FM,302214,47154,07:55:00
1,None,1.0,Thrissur Guruvayur Passenger,THRISUR,TCR,281458,56044,18:55:00
2,None,1.0,Porbandar Muzaffarpur Express,PORBANDAR,PBR,309335,19269,15:05:00
3,None,1.0,RAIPUR ITWARI PASS,RAIPUR JN,R,283774,58205,13:30:00
4,None,1.0,Gomoh-Asansol MEMU,GOMOH JN,GMO,319937,63542,07:20:00

In [5]:
import pandas as pd

def preprocess_json(df):

    print("=" * 60)
    print("Original Shape:", df.shape)

    # Remove rows where all values are missing
    df = df.dropna(how="all")

    # Fill missing values
    for col in df.columns:

        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())

        else:
            mode = df[col].mode()

            if not mode.empty:
                df[col] = df[col].fillna(mode.iloc[0])

    print("Final Shape:", df.shape)

    print("\nMissing Values")
    print(df.isnull().sum())

    return df

In [3]:
import pandas as pd
schedule = pd.read_json("../datasets/schedules.json")

In [6]:
schedule = preprocess_json(schedule)

============================================================
Original Shape: (417080, 8)
Final Shape: (417080, 8)

Missing Values
arrival         0
day             0
train_name      0
station_name    0
station_code    0
id              0
train_number    0
departure       0
dtype: int64

In [9]:
schedule.to_json(
    "../outputs/schedules_cleaned.json",
    orient="records",
    indent=4
)

In [10]:
stations = pd.read_json("../datasets/stations.json")

print(stations.columns)

stations.head()

Index(['type', 'features'], dtype='str')

                type                                           features
0  FeatureCollection  {'geometry': {'type': 'Point', 'coordinates': ...
1  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
2  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
3  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
4  FeatureCollection  {'geometry': {'type': 'Point', 'coordinates': ...

In [11]:
stations = pd.read_json("../datasets/stations.json")

print(stations.columns)

stations.head()

Index(['type', 'features'], dtype='str')

                type                                           features
0  FeatureCollection  {'geometry': {'type': 'Point', 'coordinates': ...
1  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
2  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
3  FeatureCollection  {'geometry': None, 'type': 'Feature', 'propert...
4  FeatureCollection  {'geometry': {'type': 'Point', 'coordinates': ...

In [12]:
stations = pd.json_normalize(stations["features"])

In [13]:
stations.head()

,type,geometry.type,geometry.coordinates,properties.state,properties.code,properties.name,properties.zone,properties.address,geometry
0,Feature,Point,"[75.4516454, 27.2520587]",Rajasthan,BDHL,Badhal,NWR,"Kishangarh Renwal, Rajasthan",NaN
1,Feature,NaN,NaN,NaN,XX-BECE,XX-BECE,NaN,NaN,NaN
2,Feature,NaN,NaN,NaN,XX-BSPY,XX-BSPY,NaN,NaN,NaN
3,Feature,NaN,NaN,NaN,YY-BPLC,YY-BPLC,NaN,NaN,NaN
4,Feature,Point,"[79.519746, 28.913427000000002]",Uttar Pradesh,KHH,KICHHA,NER,"Kichha, Uttar Pradesh",NaN

In [14]:
import pandas as pd

def preprocess_json(df):

    print("=" * 60)
    print("Original Shape:", df.shape)

    # Remove completely empty rows
    df = df.dropna(how="all")

    for col in df.columns:

        # Skip columns that contain lists or dictionaries
        if df[col].apply(lambda x: isinstance(x, (list, dict))).any():
            print(f"Skipping complex column: {col}")
            continue

        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())
        else:
            mode = df[col].mode()
            if not mode.empty:
                df[col] = df[col].fillna(mode.iloc[0])

    print("\nMissing Values")
    print(df.isnull().sum())

    return df

In [15]:
stations = preprocess_json(stations)

============================================================
Original Shape: (8990, 9)
Skipping complex column: geometry.coordinates

Missing Values
type                       0
geometry.type              0
geometry.coordinates     293
properties.state           0
properties.code            0
properties.name            0
properties.zone            0
properties.address         0
geometry                8990
dtype: int64

In [19]:
stations.to_json(
    "../outputs/stations_cleaned.json",
    orient="records",
    indent=4
)

In [17]:
stations = stations.drop(columns=["geometry"])

In [18]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 8990 entries, 0 to 8989
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  8990 non-null   str
 1   geometry.type         8990 non-null   str
 2   geometry.coordinates  8697 non-null   object
 3   properties.state      8990 non-null   str
 4   properties.code       8990 non-null   str
 5   properties.name       8990 non-null   str
 6   properties.zone       8990 non-null   str
 7   properties.address    8990 non-null   str
dtypes: object(1), str(7)
memory usage: 562.0+ KB

In [20]:
trains = pd.read_json("../datasets/trains.json")

print(trains.columns)

trains.head()

Index(['type', 'features'], dtype='str')

                type                                           features
0  FeatureCollection  {'geometry': {'type': 'LineString', 'coordinat...
1  FeatureCollection  {'geometry': {'type': 'LineString', 'coordinat...
2  FeatureCollection  {'geometry': {'type': 'LineString', 'coordinat...
3  FeatureCollection  {'geometry': {'type': 'LineString', 'coordinat...
4  FeatureCollection  {'geometry': {'type': 'LineString', 'coordinat...

In [21]:
trains = pd.json_normalize(trains["features"])

In [22]:
trains.head()

,type,geometry.type,geometry.coordinates,properties.third_ac,properties.arrival,properties.from_station_code,properties.name,properties.zone,properties.chair_car,properties.first_class,...,properties.departure,properties.return_train,properties.to_station_code,properties.second_ac,properties.classes,properties.to_station_name,properties.duration_h,properties.type,properties.first_ac,properties.distance
0,Feature,LineString,"[[74.880117, 32.706975], [74.953339, 32.762368...",0,12:15:00,JAT,Jammu Tawi Udhampur Special,NR,0,0,...,10:40:00,04602,UHP,0,,UDHAMPUR,1.0,DEMU,0,53.0
1,Feature,LineString,"[[75.154881, 32.92664], [75.14542599999999, 32...",0,08:35:00,UHP,UDHAMPUR JAMMUTAWI DMU,NR,0,0,...,06:45:00,04601,JAT,0,,JAMMU TAWI,1.0,DEMU,0,53.0
2,Feature,LineString,"[[74.880117, 32.706975], [74.953339, 32.762368...",0,17:50:00,JAT,JAT UDAHMPUR DMU,NR,0,0,...,16:15:00,04604,UHP,0,,UDHAMPUR,1.0,DEMU,0,53.0
3,Feature,LineString,"[[75.154881, 32.92664], [75.14542599999999, 32...",0,19:50:00,UHP,UDHAMPUR JAMMUTAWI DMU,NR,0,0,...,18:20:00,04603,JAT,0,,JAMMU TAWI,1.0,DEMU,0,53.0
4,Feature,LineString,"[[72.840535, 19.061911], [72.840078, 19.069166...",1,12:30:00,BDTS,Mumbai BandraT-Bikaner SF Special,NWR,0,0,...,14:35:00,04727,BKN,1,,BIKANER JN,21.0,SF,0,1212.0

In [23]:
trains = preprocess_json(trains)

============================================================
Original Shape: (5208, 24)
Skipping complex column: geometry.coordinates

Missing Values
type                            0
geometry.type                   0
geometry.coordinates            0
properties.third_ac             0
properties.arrival              0
properties.from_station_code    0
properties.name                 0
properties.zone                 0
properties.chair_car            0
properties.first_class          0
properties.duration_m           0
properties.sleeper              0
properties.from_station_name    0
properties.number               0
properties.departure            0
properties.return_train         0
properties.to_station_code      0
properties.second_ac            0
properties.classes              0
properties.to_station_name      0
properties.duration_h           0
properties.type                 0
properties.first_ac             0
properties.distance             0
dtype: int64

In [24]:
trains.columns

Index(['type', 'geometry.type', 'geometry.coordinates', 'properties.third_ac',
       'properties.arrival', 'properties.from_station_code', 'properties.name',
       'properties.zone', 'properties.chair_car', 'properties.first_class',
       'properties.duration_m', 'properties.sleeper',
       'properties.from_station_name', 'properties.number',
       'properties.departure', 'properties.return_train',
       'properties.to_station_code', 'properties.second_ac',
       'properties.classes', 'properties.to_station_name',
       'properties.duration_h', 'properties.type', 'properties.first_ac',
       'properties.distance'],
      dtype='str')

In [26]:
trains.to_json(
    "../outputs/trains_cleaned.json",
    orient="records",
    indent=4
)